-- Generated from schema.prisma. Apply with: npm run prisma:deploy
CREATE TABLE `users` (`id` VARCHAR(191) NOT NULL, `name` VARCHAR(191) NOT NULL, `email` VARCHAR(191) NOT NULL, `password_hash` VARCHAR(191) NOT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL, UNIQUE INDEX `users_email_key`(`email`), PRIMARY KEY (`id`));
CREATE TABLE `applications` (`id` VARCHAR(191) NOT NULL, `full_name` VARCHAR(191) NOT NULL, `webfile_number` VARCHAR(191) NOT NULL, `email` VARCHAR(191) NOT NULL, `primary_phone` VARCHAR(191) NOT NULL, `otp_receiver_phone` VARCHAR(191) NOT NULL, `notes` TEXT NULL, `status` ENUM('DRAFT','ACTIVE','ARCHIVED') NOT NULL DEFAULT 'DRAFT', `automation_status` ENUM('NOT_STARTED','QUEUED','PAUSED','FAILED') NOT NULL DEFAULT 'NOT_STARTED', `assigned_user_id` VARCHAR(191) NULL, `created_by` VARCHAR(191) NOT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL, UNIQUE INDEX `applications_webfile_number_key`(`webfile_number`), INDEX `applications_full_name_idx`(`full_name`), INDEX `applications_primary_phone_idx`(`primary_phone`), INDEX `applications_status_idx`(`status`), INDEX `applications_assigned_user_id_idx`(`assigned_user_id`), PRIMARY KEY (`id`));
CREATE TABLE `application_credentials` (`id` VARCHAR(191) NOT NULL, `application_id` VARCHAR(191) NOT NULL, `login_phone` VARCHAR(191) NOT NULL, `encrypted_login_password` TEXT NOT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL, UNIQUE INDEX `application_credentials_application_id_key`(`application_id`), PRIMARY KEY (`id`));
CREATE TABLE `appointment_preferences` (`id` VARCHAR(191) NOT NULL, `application_id` VARCHAR(191) NOT NULL, `mission` VARCHAR(191) NOT NULL, `ivac_centre` VARCHAR(191) NOT NULL, `visa_type` VARCHAR(191) NOT NULL, `preferred_date` DATE NULL, `allow_alternative_dates` BOOLEAN NOT NULL DEFAULT false, `allowed_date_from` DATE NULL, `allowed_date_to` DATE NULL, UNIQUE INDEX `appointment_preferences_application_id_key`(`application_id`), INDEX `appointment_preferences_mission_ivac_centre_visa_type_idx`(`mission`, `ivac_centre`, `visa_type`), PRIMARY KEY (`id`));
CREATE TABLE `application_documents` (`id` VARCHAR(191) NOT NULL, `application_id` VARCHAR(191) NOT NULL, `kind` ENUM('BGDR') NOT NULL DEFAULT 'BGDR', `original_filename` VARCHAR(191) NOT NULL, `mime_type` VARCHAR(191) NOT NULL, `size` INTEGER NOT NULL, `stored_path` VARCHAR(191) NOT NULL, `uploaded_by` VARCHAR(191) NOT NULL, `uploaded_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), UNIQUE INDEX `application_documents_stored_path_key`(`stored_path`), UNIQUE INDEX `application_documents_application_id_kind_key`(`application_id`, `kind`), PRIMARY KEY (`id`));
CREATE TABLE `application_events` (`id` VARCHAR(191) NOT NULL, `application_id` VARCHAR(191) NOT NULL, `actor_id` VARCHAR(191) NOT NULL, `type` VARCHAR(191) NOT NULL, `message` VARCHAR(500) NOT NULL, `metadata` JSON NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), INDEX `application_events_application_id_created_at_idx`(`application_id`, `created_at`), PRIMARY KEY (`id`));
ALTER TABLE `applications` ADD CONSTRAINT `applications_assigned_user_id_fkey` FOREIGN KEY (`assigned_user_id`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `applications` ADD CONSTRAINT `applications_created_by_fkey` FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `application_credentials` ADD CONSTRAINT `application_credentials_application_id_fkey` FOREIGN KEY (`application_id`) REFERENCES `applications`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `appointment_preferences` ADD CONSTRAINT `appointment_preferences_application_id_fkey` FOREIGN KEY (`application_id`) REFERENCES `applications`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `application_documents` ADD CONSTRAINT `application_documents_application_id_fkey` FOREIGN KEY (`application_id`) REFERENCES `applications`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `application_documents` ADD CONSTRAINT `application_documents_uploaded_by_fkey` FOREIGN KEY (`uploaded_by`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `application_events` ADD CONSTRAINT `application_events_application_id_fkey` FOREIGN KEY (`application_id`) REFERENCES `applications`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `application_events` ADD CONSTRAINT `application_events_actor_id_fkey` FOREIGN KEY (`actor_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
