export type ErrorDisposition='RETRYABLE'|'OPERATOR_ACTION_REQUIRED'|'PERMANENT'
const operator=new Set(['SESSION_LOST','VERIFICATION_REQUIRED','OTP_MATCH_AMBIGUOUS','OTP_EXPIRED','OTP_ALREADY_USED','LOGIN_INVALID_CREDENTIALS','DOCUMENT_INVALID','DOCUMENT_MISSING','MISSION_NOT_CONFIGURED','MISSION_NOT_AVAILABLE','CENTRE_NOT_CONFIGURED','CENTRE_NOT_AVAILABLE','PAYMENT_FAILED_MANUAL'])
const retryable=/timeout|network|ECONNRESET|TEMPORARY_SERVER_ERROR|5\d\d/i
export class WorkerErrorClassifier { classify(code:string):ErrorDisposition{return operator.has(code)?'OPERATOR_ACTION_REQUIRED':retryable.test(code)?'RETRYABLE':'PERMANENT'} }
