import { Router } from 'express'
import { randomBytes } from 'node:crypto'
import bcrypt from 'bcryptjs'
import { z } from 'zod'
import { prisma } from './prisma.js'
import { decryptSecret } from './crypto.js'

const internal = Router()
const states = ['QUEUED','STARTING','OPENING_BROWSER','LOGGING_IN','CHECK_VERIFICATION','VERIFICATION_REQUIRED','LOGIN_SUBMITTED','OTP_PAGE_REACHED','REQUESTING_OTP','WAITING_FOR_OTP','OTP_RECEIVED','SUBMITTING_OTP','AUTHENTICATED','OTP_TIMEOUT','OTP_REJECTED','OTP_MATCH_AMBIGUOUS','NEEDS_ATTENTION','UPLOADING_DOCUMENT','DOCUMENT_UPLOADED','CONFIRMING_INFORMATION','SELECTING_MISSION','SELECTING_CENTRE','WAITING_FOR_SLOT','SLOT_FOUND','SELECTING_DATE','DATE_SELECTED','CONTINUING_BOOKING','PREPARING_PAYMENT','PAYMENT_READY','PAUSED','RETRYING','FAILED','CANCELLED','COMPLETED'] as const
type InternalRequest = any & { workerId: string }
async function workerAuth(req: any, res: any, next: any) { const name = req.header('x-worker-name'); const key = req.header('x-worker-key'); const worker = name && key ? await prisma.automationWorker.findUnique({ where: { workerName: name } }) : null; if (!worker || !(await bcrypt.compare(key, worker.apiKeyHash))) return res.status(401).json({ error: 'Worker authentication failed' }); req.workerId = worker.id; next() }
// Registration is deliberately unavailable in production unless an operator provisions a record/secret out of band.
internal.post('/workers/register', async (req, res) => { const secret = process.env.INTERNAL_WORKER_REGISTRATION_SECRET; if (!secret || req.header('x-registration-secret') !== secret) return res.status(403).json({ error: 'Worker provisioning is disabled' }); const input = z.object({ workerName: z.string().min(3).max(191) }).safeParse(req.body); if (!input.success) return res.status(422).json({ error: 'Invalid worker name' }); const key = randomBytes(32).toString('base64url'); const worker = await prisma.automationWorker.upsert({ where: { workerName: input.data.workerName }, update: { apiKeyHash: await bcrypt.hash(key, 12), status: 'ONLINE', lastHeartbeatAt: new Date() }, create: { workerName: input.data.workerName, apiKeyHash: await bcrypt.hash(key, 12), status: 'ONLINE', lastHeartbeatAt: new Date() } }); res.status(201).json({ worker: { id: worker.id, workerName: worker.workerName }, apiKey: key }) })
internal.use(workerAuth)
internal.post('/workers/heartbeat', async (req: InternalRequest, res) => { await prisma.automationWorker.update({ where: { id: req.workerId }, data: { status: 'ONLINE', lastHeartbeatAt: new Date() } }); res.json({ ok: true }) })
internal.post('/commands/next', async (req:InternalRequest,res)=>{await prisma.workerCommand.updateMany({where:{workerId:req.workerId,status:'PENDING',expiresAt:{lt:new Date()}},data:{status:'EXPIRED'}});const command=await prisma.workerCommand.findFirst({where:{workerId:req.workerId,status:'PENDING',expiresAt:{gt:new Date()}},orderBy:{createdAt:'asc'}});if(!command)return res.json({command:null});const claimed=await prisma.workerCommand.updateMany({where:{id:command.id,status:'PENDING'},data:{status:'CLAIMED',acknowledgedAt:new Date()}});if(!claimed.count)return res.json({command:null});res.json({command:{id:command.id,jobId:command.jobId,commandType:command.commandType}})})
internal.post('/commands/:id/ack',async(req:InternalRequest,res)=>{const input=z.object({ok:z.boolean(),errorCode:z.string().max(100).optional()}).parse(req.body);const command=await prisma.workerCommand.findFirst({where:{id:req.params.id,workerId:req.workerId,status:'CLAIMED'}});if(!command)return res.status(409).json({error:'Command unavailable'});await prisma.workerCommand.update({where:{id:command.id},data:{status:input.ok?'COMPLETED':'FAILED',errorCode:input.errorCode,completedAt:new Date()}});res.json({ok:true})})
internal.post('/jobs/:id/claim', async (req: InternalRequest, res) => { const job = await prisma.automationJob.updateMany({ where: { id: req.params.id, state: 'QUEUED', workerId: null }, data: { workerId: req.workerId, claimedAt: new Date(), state: 'STARTING' } }); if (!job.count) return res.status(409).json({ error: 'Job cannot be claimed' }); await prisma.automationJobEvent.create({ data: { jobId: req.params.id, state: 'STARTING', message: 'Job claimed by worker' } }); res.json({ claimed: true }) })
internal.get('/jobs/next', async (_req: InternalRequest, res) => { const job = await prisma.automationJob.findFirst({ where: { state: 'QUEUED', workerId: null }, orderBy: { createdAt: 'asc' }, select: { id: true } }); res.json({ job }) })
internal.get('/jobs/:id/context', async (req: InternalRequest, res) => { const job = await prisma.automationJob.findFirst({ where: { id: req.params.id, workerId: req.workerId }, include: { application: { include: { preference: true, documents: true, credentials: true } } } }); if (!job) return res.status(404).json({ error: 'Job not found' }); const { credentials, ...application } = job.application; if (!credentials) return res.status(422).json({ error: 'Missing IVAC credentials' }); res.json({ id: job.id, state: job.state, application, login: { phone: credentials.loginPhone, password: decryptSecret(credentials.encryptedLoginPassword) }, fixtureMode: false }) })
internal.post('/jobs/:id/status', async (req: InternalRequest, res) => { const input = z.object({ state: z.enum(states), message: z.string().max(500).default('State transition'), diagnostics: z.object({ url: z.string().max(2000).optional(), title: z.string().max(500).optional(), expectedSelector: z.string().max(500).optional(), errorCode: z.string().max(100).optional(), screenshotPath: z.string().max(1000).optional() }).optional() }).safeParse(req.body); if (!input.success) return res.status(422).json({ error: 'Invalid state report' }); const job = await prisma.automationJob.findFirst({ where: { id: req.params.id, workerId: req.workerId } }); if (!job) return res.status(404).json({ error: 'Job not found' }); await prisma.$transaction([prisma.automationJob.update({ where: { id: job.id }, data: { state: input.data.state, pausedAt: input.data.state === 'VERIFICATION_REQUIRED' || input.data.state === 'PAUSED' ? new Date() : null } }), prisma.automationJobEvent.create({ data: { jobId: job.id, state: input.data.state, message: input.data.message, diagnostics: input.data.diagnostics } })]); res.json({ ok: true }) })
internal.post('/jobs/:id/failure', async (req: InternalRequest, res) => { const input = z.object({ code: z.string().max(100), message: z.string().max(500) }).safeParse(req.body); if (!input.success) return res.status(422).json({ error: 'Invalid failure' }); await prisma.automationJob.update({ where: { id: req.params.id, workerId: req.workerId }, data: { state: 'FAILED', lastErrorCode: input.data.code } }); await prisma.automationJobEvent.create({ data: { jobId: req.params.id, state: 'FAILED', message: input.data.message, diagnostics: { errorCode: input.data.code } } }); res.json({ ok: true }) })
internal.post('/jobs/:id/otp/claim', async (req: InternalRequest, res) => { const job = await prisma.automationJob.findFirst({ where: { id: req.params.id, workerId: req.workerId, state: 'WAITING_FOR_OTP' }, select: { id: true } }); if (!job) return res.status(404).json({ error: 'OTP_NOT_AVAILABLE' }); const matches = await prisma.otpMatch.findMany({ where: { automationJobId: job.id, consumedAt: null, expiresAt: { gt: new Date() } }, orderBy: { matchedAt: 'desc' }, take: 2 }); if (!matches.length) return res.status(404).json({ error: 'OTP_NOT_AVAILABLE' }); if (matches.length > 1) return res.status(409).json({ error: 'OTP_MATCH_AMBIGUOUS' }); const match = matches[0]; res.json({ id: match.id, otp: decryptSecret(match.encryptedOtpValue), expiresAt: match.expiresAt }) })
internal.post('/jobs/:id/otp/:otpId/consume', async (req: InternalRequest, res) => { const job = await prisma.automationJob.findFirst({ where: { id: req.params.id, workerId: req.workerId, state: 'SUBMITTING_OTP' }, select: { id: true } }); if (!job) return res.status(409).json({ error: 'OTP_ALREADY_USED_OR_UNAVAILABLE' }); const consumed = await prisma.otpMatch.updateMany({ where: { id: req.params.otpId, automationJobId: job.id, consumedAt: null, expiresAt: { gt: new Date() } }, data: { consumedAt: new Date() } }); if (!consumed.count) return res.status(409).json({ error: 'OTP_ALREADY_USED_OR_UNAVAILABLE' }); await prisma.automationJobEvent.create({ data: { jobId: job.id, state: 'SUBMITTING_OTP', message: 'OTP_CONSUMED' } }); res.json({ ok: true }) })
export { internal }
