export type Application = { id: string; fullName: string; webfileNumber: string; email: string; primaryPhone: string; otpReceiverPhone: string; notes?: string | null; status: 'DRAFT'|'ACTIVE'|'ARCHIVED'; automationStatus: string; createdAt: string; updatedAt: string; preference?: { mission: string; ivacCentre: string; visaType: string; preferredDate?: string | null; allowAlternativeDates: boolean; allowedDateFrom?: string | null; allowedDateTo?: string | null } | null; documents: { id: string; originalFilename: string; mimeType: string; size: number; uploadedAt: string }[]; events?: { id: string; type: string; message: string; createdAt: string; actor: { name: string } }[] }
const base = import.meta.env.VITE_API_URL ?? 'http://localhost:4000/api'
const token = () => localStorage.getItem('ivac_access_token') ?? import.meta.env.VITE_API_TOKEN
async function request<T>(path: string, init: RequestInit = {}): Promise<T> { const response = await fetch(`${base}${path}`, { ...init, headers: { ...(init.body instanceof FormData ? {} : { 'Content-Type': 'application/json' }), ...(token() ? { Authorization: `Bearer ${token()}` } : {}), ...init.headers } }); if (!response.ok) throw new Error((await response.json().catch(() => ({ error: 'Request failed' }))).error); return response.status === 204 ? undefined as T : response.json() }
export type Sms = { id:string; receivedAt:string; receiverNumber:string; senderNumber:string; status:string; detectedOtp:string|null; otpStatus:'AVAILABLE'|'CONSUMED'|'EXPIRED'|'AMBIGUOUS'|null; jobId:string|null; collector:{deviceName:string}; matchedApplication?:{id:string;fullName:string;webfileNumber:string}|null }
export type Collector = { id:string; deviceName:string; phoneNumber:string; status:'ONLINE'|'DEGRADED'|'OFFLINE'|'DISABLED'; lastHeartbeatAt:string|null; lastSmsReceivedAt:string|null }
export type CollectorPairing = { collector: { id:string; deviceName:string; phoneNumber:string; status:string }; pairingCode:string; expiresAt:string }
export type AutomationJob = { id: string; state: string; retryCount: number; lastErrorCode: string | null; updatedAt: string; application: { id: string; fullName: string; webfileNumber: string }; worker: { id: string; workerName: string; lastHeartbeatAt: string | null; status: string } | null; latestEvent: { state: string; event: string; errorCode?: string; timestamp: string } | null }
export const api = { list: (search = '') => request<{data: Application[]}>(`/applications?search=${encodeURIComponent(search)}`), get: (id: string) => request<Application>(`/applications/${id}`), create: (body: unknown) => request<Application>('/applications', { method: 'POST', body: JSON.stringify(body) }), update: (id: string, body: unknown) => request<Application>(`/applications/${id}`, { method: 'PUT', body: JSON.stringify(body) }), upload: (id: string, document: File) => { const body = new FormData(); body.append('document', document); return request(`/applications/${id}/document`, { method:'POST', body }) }, documentUrl: (id: string) => `${base}/applications/${id}/document`, sms: () => request<{data: Sms[]}>('/sms'), collectors: () => request<{data:Collector[]}>('/collectors'), createCollectorPairing: (body:{deviceName:string;phoneNumber:string;backendUrl:string}) => request<CollectorPairing>('/collectors/pairings', { method:'POST', body:JSON.stringify(body) }), regenerateCollectorPairing: (id:string, backendUrl:string) => request<CollectorPairing>(`/collectors/${id}/pairings`, { method:'POST', body:JSON.stringify({ backendUrl }) }), setCollectorStatus: (id:string, action:'enable'|'disable') => request<{collector:Collector}>(`/collectors/${id}/status`, { method:'PATCH', body:JSON.stringify({ action }) }), assignSms: (id:string, applicationId:string) => request(`/sms/${id}/assign`, { method:'PUT', body:JSON.stringify({ applicationId }) }), createAutomationJob:(applicationId:string)=>request<{id:string;applicationId:string;state:string;createdAt:string;updatedAt:string}>(`/applications/${applicationId}/automation-jobs`,{method:'POST'}), jobs:()=>request<{data:AutomationJob[]}>('/jobs'), command:(jobId:string,type:string)=>request<any>(`/jobs/${jobId}/commands/${type}`,{method:'POST'}), commandStatus:(jobId:string,id:string)=>request<any>(`/jobs/${jobId}/commands/${id}`) }
